package:
  name: metax
  version: "0.9.12"            # change to your actual version

build:
  number: 0
  # noarch: generic

source:
  # Use the current recipe directory as source (contains the binary)
  path: .

requirements:
  run:
    - ma ==1.1.4

about:
  home: https://github.com/hzi-bifo/Metax
  license: ASL
  summary: "A Coverage-Informed Probabilistic Framework for Accurate Cross-Domain Taxon Profiling"

extra:
  recipe-maintainers:
    - zldeng
